#!/bin/bash
##############################
# GTK launcher specific part #
##############################

# shellcheck disable=SC2154
if [ "$wayland_available" = true ]; then
  export GDK_BACKEND="wayland"
  export CLUTTER_BACKEND="wayland"
  # Does not hurt to specify this as well, just in case
  export QT_QPA_PLATFORM=wayland-egl
fi
append_dir GTK_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/gtk-2.0"
append_dir GTK_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/gtk-2.0"
append_dir GTK_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/gtk-3.0"
append_dir GTK_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/gtk-3.0"
append_dir GTK_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/gtk-4.0"
append_dir GTK_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/gtk-4.0"

snap_python_version="%WITH_PYTHON%"
if [ "$snap_python_version" = "3.6" ]; then
  append_dir PYTHONPATH "$SNAP_DESKTOP_RUNTIME/usr/lib/python3.6/site-packages"
else # python version is 3.8 or higher.
  append_dir PYTHONPATH "$SNAP_DESKTOP_RUNTIME/usr/lib/python$snap_python_version"
fi
append_dir PYTHONPATH "$SNAP_DESKTOP_RUNTIME/usr/lib/python3/dist-packages"

# ibus and fcitx integration
GTK_IM_MODULE_DIR="$XDG_CACHE_HOME/immodules"
export GTK_IM_MODULE_FILE="$GTK_IM_MODULE_DIR/immodules.cache"
# shellcheck disable=SC2154
if [ "$needs_update" = true ]; then
  rm -rf "$GTK_IM_MODULE_DIR"
  ensure_dir_exists "$GTK_IM_MODULE_DIR"
  ln -s "$SNAP_DESKTOP_RUNTIME"/usr/lib/"$ARCH"/gtk-3.0/3.0.0/immodules/*.so "$GTK_IM_MODULE_DIR"
  async_exec "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/libgtk-3-0/gtk-query-immodules-3.0" > "$GTK_IM_MODULE_FILE"
fi

# override the notification backend when detecting an old version of the desktop portal,
# that is known not to match the snap appId correctly
function configure_notification_backend() {
  if ! gdbus call --session -d org.freedesktop.portal.Desktop \
                              -o /org/freedesktop/portal/desktop \
                              -m org.freedesktop.DBus.Properties.Get \
                              "org.freedesktop.portal.GlobalShortcuts" \
                              "version" >/dev/null; then
    async_export GNOTIFICATION_BACKEND=freedesktop NOTIFY_IGNORE_PORTAL=1
  fi
}
async_exec_with_exports configure_notification_backend
